config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  resources :toppages, only: %i[index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :favorites, only:[:create, :destroy]

  resources :users
  resources :blogs
  resources :searchs

  resources :selections do
    resources :voters do
      resources :vote_actions, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :toppages
    resources :users
  end

  resources :prefs do
    resources :politicians
    resources :zones, only: [:index, :show] do
      resources :results
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/politician.rb
class Politician < ApplicationRecord
  belongs_to :user
  belongs_to :pref
  belongs_to :zone
  has_many :vote_actions, dependent: :destroy
  has_many :vote_voters, through: :vote_actions, source: :vote
end

app/models/pref.rb
class Pref < ApplicationRecord
  validates :pref_name, presence: true

  has_many :politicians, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :zones, dependent: :destroy
end

app/models/selection.rb
class Selection < ApplicationRecord
  has_many :voters, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :voters, dependent: :destroy
  has_many :politicians, dependent: :destroy
  has_many :blogs, dependent: :destroy
  belongs_to :pref
  belongs_to :zone
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/vote_action.rb
class VoteAction < ApplicationRecord
  belongs_to :voter
  belongs_to :politician

  validates :voter_id, :uniqueness => {:scope => :selection_id}
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :user
  belongs_to :selection

  has_many :vote_actions, dependent: :destroy
  has_many :vote_politicians, through: :vote_actions, source: :politician

  validates :user_id, :uniqueness => {:scope => :selection_id}

end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :pref
  has_many :politicians, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def create
    @blog = Blog.new(blog_parameter)
    @blog.user_id = current_user.id

    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
    
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time,:user_id)
  end
end

app/controllers/prefs_controller.rb
class PrefsController < ApplicationController
  def index
    nums = [*(1..47)]
    @prefs = Pref.where(id: nums)
  end

  def show
    @pref = Pref.find(params[:id])
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
    @politicians = Politician.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to login_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_image, :age, :sex, :pref_id, :zone, :zone_id)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def index
    @selection = Selection.find(params[:selection_id])
    @voters = Voter.where(user_id: current_user).where(selection_id: @selection.id)
  end

  def new
    @selection = Selection.find(params[:selection_id])
    @voter = @selection.voters.build
    respond_to do |format|
      format.html{ redirect_to @voter, notice: 'User was successfully created.' }
      format.js {}
    end
  end

  def create
    @selection = Selection.find(params[:selection_id])
    @voter = @selection.voters.build(voter_params)
    @voter.user_id = current_user.id
    @voter.selection_id = @selection.id
    respond_to do |format|
      if @voter.save
        format.html { redirect_to selection_voters_path(@selection)}
      else
        format.html { render :new }
      end
    end
  end

  def show
    @selection = Selection.find(params[:selection_id])
    @voter = Voter.find(params[:id])
    @pref = Pref.find(params[:id])
    @politicians = Politician.all
    @vote_action = @voter.vote_actions.build
  end


  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy
    redirect_to selection_voters_path
  end

  private

  def voter_params
    params.require(:voter).permit(:user_id, :selection_id, :nickname, :pref_id, :politician_id)
  end

end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  def index
    nums = [*(1..15)]
    @zones = Zone.where(id: nums)
    @pref = Pref.find(params[:pref_id])
  end

  def show
    @pref = Pref.find(params[:pref_id])
    @zone = Zone.find(params[:id])
    @politicians = Politician.where(pref_id: @pref.id).where(zone_id: @zone.id)
    @vote_actions = VoteAction.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/blogs/edit.html.haml
= form_with(model: @blog, local: true) do |form|
  .title
    = form.label :title
    = form.text_field :title
  .time
    = form.label :start_time
    = form.datetime_select :start_time
  .content
    = form.label :content
    = form.text_field :content
  .submit
    = form.submit

app/views/blogs/index.html.haml
%p#notice= notice
%h1 自分の日記
%table
  %thead
    %tr
      %th タイトル
      %th 時間
      %th{:colspan => "3"}
  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= blog.start_time.strftime("%Y-%m-%d %H:%M")
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog.id)
        %td= link_to 'Destroy',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to '日記をかく', new_blog_path
= month_calendar events: @blogs do |date, blogs|
  = date.day
  - blogs.each do |blog|
    %div
      = link_to blog.title, blog

app/views/blogs/new.html.haml
= form_with(model: @blog, local: true) do |form|
  .title
    = form.label :title
    = form.text_field :title
  .time
    = form.label :start_time
    = form.datetime_select :start_time
  .content
    = form.label :content
    = form.text_field :content
  .submit
    = form.submit

app/views/blogs/show.html.haml
%p#notice= notice
%p
  %strong タイトル
  = @blog.title
%p
  %strong 時間
  = @blog.start_time.strftime("%Y-%m-%d %H:%M")
%p
  %strong 内容
  = @blog.content
= link_to 'Edit', edit_blog_path(@blog)
|
= link_to 'Back', blogs_path

- unless @blog.user_id == current_user.id
  - if @favorite.present?
    = link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger'
  - else
    = link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary'

app/views/searchs/index.html.haml
%h3.title 政治家一覧
%table
  %thead
    %tr
      %th 名前
  %tbody
    - @politicians.each do |politician|
      %tr
        %td= politician.name

%ul#tab
  %li.square_btn.select 北海道
  %li.square_btn 東北
  %li.square_btn 関東
  %li.square_btn 北陸
  %li.square_btn 東海
  %li.square_btn 近畿
  %li.square_btn 中国
  %li.square_btn 四国
  %li.square_btn 九州
.clear
.content_wrap
  %li.square_btn 東北
  %li.square_btn 関東
  %li.square_btn 北陸
.content_wrap.disnon 内容2
  %li.square_btn 東北
  %li.square_btn 関東
  %li.square_btn 北陸
.content_wrap.disnon 内容3
  %li.square_btn 東北
  %li.square_btn 関東
  %li.square_btn 北陸
.content_wrap.disnon 内容4

:javascript
  $(function() {
      $("#tab li").click(function() {
          var num = $("#tab li").index(this);
          $(".content_wrap").addClass('disnon');
          $(".content_wrap").eq(num).removeClass('disnon');
          $("#tab li").removeClass('select');
          $(this).addClass('select')
      });
  });

app/views/voters/_form.html.haml
.modal-dialog
  .modal-content
    %h3 電子投票を行う場合は以下のボタンを押してください
    %h5 注意　電子投票を行う場合は市町村に設置されている投票箱での投票はできません
    =form_with model: [@selection, @voter], local: true do |f|
      .form-group
        = f.hidden_field :nickname, class: "form-control"
      = f.submit '選挙登録', class: "btn btn-primary button_wrapper"

app/views/voters/index.html.haml
%h3 #{@selection.select_name}の選挙

%div= link_to "投票事前登録", new_selection_voter_path, remote: true, class: "btn btn-lg btn-primary"
#voter-modal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}

- @voters.each do |voter|
  - if voter.user.present?
    .main
      .wrapper
        .container_top
          %dl
            %dt 自分の氏名
            - @voters.each do |voter|
              %dd= voter.user.name
              - unless voter.vote_actions.present?
                %dd= link_to "投票を行う", selection_voter_path(@selection, voter), class: "btn btn-success"
              - else
                %dd= "投票済"
        .container_down
          %dl
            %dt 投票した人
            - @voters.each do |voter|
              - voter.vote_politicians.each do |action|
                %dd= action.name
    .link
      .link_contain
        - @voters.each do |voter|
          %tr
            %td= link_to "やり直す", selection_voter_path(@selection, voter), method: :delete,remote: true, data: { confirm: "削除します"}, class: "btn btn-danger delete"

      

app/views/voters/new.html.haml
%h1 ２回目の登録はできません。

app/views/voters/new.js.haml
$("#voter-modal").html("#{escape_javascript(render 'form')}")
$("#voter-modal").modal("show")

app/views/voters/show.html.haml
= render 'politicians/index', politicians: @politicians, selection: @selection, vote_action: @vote_action

app/views/zones/index.html.haml
%h3.title 選挙
%table
  %thead
    %tr
      %th 選挙区
  %tbody
    - @zones.each do |zone|
      %tr
        %td= link_to "#{zone.zone_name}", pref_zone_path(@pref, zone)

app/views/zones/show.html.haml
%h3.title 選挙結果
%table
  %thead
    %tr
      %th 
  %tbody
    - @politicians.each do |politician|
      %tr
        %td= link_to "#{politician.name}", pref_politician_path(@pref, politician, @voter)
        %td= "#{politician.vote_actions.where(politician_id: politician).count}" "票"