config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  resources :toppages, only: %i[index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :favorites, only:[:create, :destroy]

  resources :users
  resources :blogs
  resources :searchs

  resources :selections do
    resources :voters do
      resources :vote_actions, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :toppages
    resources :users
  end

  resources :prefs do
    resources :politicians
    resources :zones, only: [:index, :show] do
      resources :results
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/politician.rb
class Politician < ApplicationRecord
  belongs_to :user
  belongs_to :pref
  belongs_to :zone
  has_many :vote_actions, dependent: :destroy
  has_many :vote_voters, through: :vote_actions, source: :vote
end

app/models/pref.rb
class Pref < ApplicationRecord
  validates :pref_name, presence: true

  has_many :politicians, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :zones, dependent: :destroy
end

app/models/selection.rb
class Selection < ApplicationRecord
  has_many :voters, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :voters, dependent: :destroy
  has_many :politicians, dependent: :destroy
  has_many :blogs, dependent: :destroy
  belongs_to :pref
  belongs_to :zone
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/vote_action.rb
class VoteAction < ApplicationRecord
  belongs_to :voter
  belongs_to :politician

  validates :voter_id, :uniqueness => {:scope => :selection_id}
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :user
  belongs_to :selection

  has_many :vote_actions, dependent: :destroy
  has_many :vote_politicians, through: :vote_actions, source: :politician

  validates :user_id, :uniqueness => {:scope => :selection_id}

end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :pref
  has_many :politicians, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/controllers/admin/toppages_controller.rb
class Admin::ToppagesController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def create
    @blog = Blog.new(blog_parameter)
    @blog.user_id = current_user.id

    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
    
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time,:user_id)
  end
end

app/controllers/prefs_controller.rb
class PrefsController < ApplicationController
  def index
    nums = [*(1..47)]
    @prefs = Pref.where(id: nums)
  end

  def show
    @pref = Pref.find(params[:id])
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
    @politicians = Politician.all
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to login_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_image, :age, :sex, :pref_id, :zone, :zone_id)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def index
    @selection = Selection.find(params[:selection_id])
    @voters = Voter.where(user_id: current_user).where(selection_id: @selection.id)
  end

  def new
    @selection = Selection.find(params[:selection_id])
    @voter = @selection.voters.build
    respond_to do |format|
      format.html{ redirect_to @voter, notice: 'User was successfully created.' }
      format.js {}
    end
  end

  def create
    @selection = Selection.find(params[:selection_id])
    @voter = @selection.voters.build(voter_params)
    @voter.user_id = current_user.id
    @voter.selection_id = @selection.id
    respond_to do |format|
      if @voter.save
        format.html { redirect_to selection_voters_path(@selection)}
      else
        format.html { render :new }
      end
    end
  end

  def show
    @selection = Selection.find(params[:selection_id])
    @voter = Voter.find(params[:id])
    @pref = Pref.find(params[:id])
    @politicians = Politician.all
    @vote_action = @voter.vote_actions.build
  end


  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy
    redirect_to selection_voters_path
  end

  private

  def voter_params
    params.require(:voter).permit(:user_id, :selection_id, :nickname, :pref_id, :politician_id)
  end

end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  def index
    nums = [*(1..15)]
    @zones = Zone.where(id: nums)
    @pref = Pref.find(params[:pref_id])
  end

  def show
    @pref = Pref.find(params[:pref_id])
    @zone = Zone.find(params[:id])
    @politicians = Politician.where(pref_id: @pref.id).where(zone_id: @zone.id)
    @vote_actions = VoteAction.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/toppages/index.html.haml
%li.nav-item= link_to "新規権限者登録", new_admin_user_path
- if current_user
  %li.nav-item= link_to "ログアウト", logout_path, method: :delete
- if current_user.admin?
  %li.nav-item= link_to "ユーザー一覧", admin_users_path
- else
  %li.nav-item= link_to "ログイン", login_path
  

app/views/toppages/index.html.haml
%head
  %meta{:charset => "utf-8"}/
  %script{:src => "jquery.min.js", :type => "text/javascript"}
  %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css", :rel => "stylesheet"}/
%body
  %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js"}
  #header
    %h1 電子投票
    / /logo
    %nav.navbar.navbar-default{:role => "navigation"}
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %span.navbar-brand.visible-xs{:href => "#"} Menu
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.first
            %li= link_to 'マップ確認', prefs_path
            %li
            %li= link_to '選挙一覧', selections_path
            %li= link_to '議員一覧', searchs_path
          -# = search_form_for @q do |f|
          -#   = f.label :name, "名前"
          -#   = f.search_field :name
          -#   .actions= f.submit "検索"
        / /.navbar-collapse
    / /nav
  / /header
  / Slider main container
  -# .swiper-container
  -#   / Additional required wrapper
  -#   .swiper-wrapper
  -#     / Slides
  -#     .swiper-slide
  -#       .test-color1 Slide 1
  -#     .swiper-slide
  -#       .test-color2 Slide 1
  -#     .swiper-slide
  -#       .test-color3 Slide 1
  -#     \...
  -#   / If we need pagination
  -#   .swiper-pagination
  -#   / If we need navigation buttons
  -#   .swiper-button-prev
  -#   .swiper-button-next
  -# :javascript
  -#   var mySwiper = new Swiper ('.swiper-container', {
  -#     effect: "flip",
  -#     loop: true,
  -#     pagination: '.swiper-pagination',
  -#     nextButton: '.swiper-button-next',
  -#     prevButton: '.swiper-button-prev',
  -#   })

%h2.heading news
%ul.scroll-list
  %li.scroll-item
    %time.date 111
    %span.category.news NEWS
    %span.title_new 更新しました
  %li.scroll-item
    %time.date 111
    %span.category NEWS
    %span.title_new 更新しました
.clearfix
  .article-box
    %h3 test
    %p test
    %time.date 1111
    %h3.title
    %p.desc
  .article-box
    %h3 test
    %p test
    %time.date 1111
    %h3.title
    %p.desc