config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  resources :toppages, only: %i[index]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :favorites, only:[:create, :destroy]

  resources :users
  resources :blogs
  resources :searchs

  resources :selections do
    resources :voters do
      resources :vote_actions, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :toppages
    resources :users
  end

  resources :prefs do
    resources :politicians
    resources :zones, only: [:index, :show] do
      resources :results
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/politician.rb
class Politician < ApplicationRecord
  belongs_to :user
  belongs_to :pref
  belongs_to :zone
  has_many :vote_actions, dependent: :destroy
  has_many :vote_voters, through: :vote_actions, source: :vote
end

app/models/pref.rb
class Pref < ApplicationRecord
  validates :pref_name, presence: true

  has_many :politicians, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :zones, dependent: :destroy
end

app/models/selection.rb
class Selection < ApplicationRecord
  has_many :voters, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :voters, dependent: :destroy
  has_many :politicians, dependent: :destroy
  has_many :blogs, dependent: :destroy
  belongs_to :pref
  belongs_to :zone
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/vote_action.rb
class VoteAction < ApplicationRecord
  belongs_to :voter
  belongs_to :politician

  validates :voter_id, :uniqueness => {:scope => :selection_id}
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :user
  belongs_to :selection

  has_many :vote_actions, dependent: :destroy
  has_many :vote_politicians, through: :vote_actions, source: :politician

  validates :user_id, :uniqueness => {:scope => :selection_id}

end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :pref
  has_many :politicians, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @q = User.search(params[:q])
    @users = @q.result.all
  end
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    head :no_content
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_image, :age, :sex, :admin, :pref_id, :zone, :zone_id)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def create
    @blog = Blog.new(blog_parameter)
    @blog.user_id = current_user.id

    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
    
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time,:user_id)
  end
end

app/controllers/prefs_controller.rb
class PrefsController < ApplicationController
  def index
    nums = [*(1..47)]
    @prefs = Pref.where(id: nums)
  end

  def show
    @pref = Pref.find(params[:id])
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
    @politicians = Politician.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to login_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_image, :age, :sex, :pref_id, :zone, :zone_id)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def index
    @selection = Selection.find(params[:selection_id])
    @voters = Voter.where(user_id: current_user).where(selection_id: @selection.id)
  end

  def new
    @selection = Selection.find(params[:selection_id])
    @voter = @selection.voters.build
    respond_to do |format|
      format.html{ redirect_to @voter, notice: 'User was successfully created.' }
      format.js {}
    end
  end

  def create
    @selection = Selection.find(params[:selection_id])
    @voter = @selection.voters.build(voter_params)
    @voter.user_id = current_user.id
    @voter.selection_id = @selection.id
    respond_to do |format|
      if @voter.save
        format.html { redirect_to selection_voters_path(@selection)}
      else
        format.html { render :new }
      end
    end
  end

  def show
    @selection = Selection.find(params[:selection_id])
    @voter = Voter.find(params[:id])
    @pref = Pref.find(params[:id])
    @politicians = Politician.all
    @vote_action = @voter.vote_actions.build
  end


  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy
    redirect_to selection_voters_path
  end

  private

  def voter_params
    params.require(:voter).permit(:user_id, :selection_id, :nickname, :pref_id, :politician_id)
  end

end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  def index
    nums = [*(1..15)]
    @zones = Zone.where(id: nums)
    @pref = Pref.find(params[:pref_id])
  end

  def show
    @pref = Pref.find(params[:pref_id])
    @zone = Zone.find(params[:id])
    @politicians = Politician.where(pref_id: @pref.id).where(zone_id: @zone.id)
    @vote_actions = VoteAction.all
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.haml
= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, "名前"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email, "メール"
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :pref_id, "都道府県"
    = f.collection_select :pref_id, Pref.all, :id, :pref_name, {prompt: "エリアを選択"}, {class: "form-control"}
  .form-group
    = f.label :zone_id, "選挙区"
    = f.collection_select :zone_id, Zone.all, :id, :zone_name, {prompt: "エリアを選択"}, {class: "form-control"}
  .form-group
    = f.label :age, "年齢"
    = f.number_field :age, class: "form-control"
  .form-check
    = f.label :admin, class: "form-check-label"
    = f.check_box :admin, class: "form-check-input"
    | 管理者権限
  .form-group
    = f.label :password, "パスワード"
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, "パスワード確認"
    = f.password_field :password_confirmation, class: "form-control"
  = f.submit "登録する", class: "btn btn-primary"

app/views/admin/users/edit.html.haml
%h1 ユーザー編集

.nav.justfy-content-end
  = link_to "一覧", admin_users_path, class: "nav-link"
= render 'form', user: @guser

app/views/admin/users/index.html.haml
%h3 ユーザー一覧


.row
  = search_form_for @q, url: '' do |f|
    .col-sm-4
      .form-group
        = f.search_field :name_cont, class: 'form-control input-sm', placeholder: '名前'
    .col-sm-2
      .form-group
        = f.submit '検索', class: 'btn btn-default btn-sm', name: nil
    .col-sm-2
      = link_to "新規登録", new_admin_user_path, class: "btn btn-primary"
.mb-3
%table.table.table-hover
  %thead.thead-default
    %tr
      %th name
      %th email
      %th admin
      %th pref
      %th create
      %th update
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, [:admin, user]
        %td= user.email
        %td= user.admin? ? "あり" : "なし"
        %td= user.pref.pref_name
        %td= user.created_at
        %td= user.updated_at
        %td
          = link_to "編集", edit_admin_user_path(user), class: "btn btn-primary mr-3"
          = link_to "削除", [:admin, user], method: :delete, remote: true, data: { confirm: "ユーザー削除します"}, class: "btn btn-danger delete"

app/views/admin/users/new.html.haml
%h1 ユーザー登録

.nav.justfy-content-end
  = link_to "一覧", admin_users_path, class: "nav-link"
= render 'form', user: @user

app/views/admin/users/show.html.haml
%h1 Admin::Users#show
%p Find me in app/views/admin/users/show.html.haml

app/views/users/_form.html.haml
= form_with model:  @user, local: true do |f|
  .form-group
    = f.label :name, "名前"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email, "メール"
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :pref_id, "都道府県"
    = f.collection_select :pref_id, Pref.all, :id, :pref_name, {prompt: "エリアを選択"}, {class: "form-control"}
  .form-group
    = f.label :zone_id, "選挙区"
    = f.collection_select :zone_id, Zone.all, :id, :zone_name, {prompt: "エリアを選択"}, {class: "form-control"}
  .form-group
    = f.label :age, "年齢"
    = f.number_field :age, class: "form-control"
  .form-group
    = f.label :password, "パスワード"
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, "パスワード確認"
    = f.password_field :password_confirmation, class: "form-control"
  = f.submit "登録する", class: "btn btn-primary"

app/views/users/edit.html.haml
%h1 ユーザー編集

.nav.justfy-content-end
= render 'form', user: @guser

app/views/users/new.html.haml
%h1 ユーザー登録

.nav.justfy-content-end
= render 'form', user: @user

app/views/users/show.html.haml
%h3 ユーザーページ